### ISSUE TITLE
Test under Linux

### ISSUE THREAD

**Issue by artificial-max** [eazteregg/Pun-Intended#6]
Test everything with Linux to make sure there are no encoding errors etc.

**Comment by lenakmeth** [comment]
Pulled and installed everything from scratch on Linux Mint 18.01. Used Python 3.6.
I will document everything I had to do to make it work, most of them were probably my fault though.
1. I downloaded the vectors zip file from the glove project, took the 100d file, put it in **generation/data**. There was no **/data** folder created in the folder where I pulled the repo. 
Running **main.py**:
2. First run, I get the error `FileNotFoundError: [Errno 2] No such file or directory: 'data'`. (Well, duh.) So I go back, and copy the data folder from generation/data to the same directory where I pulled.
3. Second run, it works! Sort of. This is the terminal output:
`Hello and welcome to the pun aid!`
`invalid literal for int() with base 10: 'the'`
`Converting gloVe to word2vec format.-------------`
`Would you like to create a binary file for your vector file, so that future loading times may be shortened? y/n`
After that, I typed `y` and everything worked fine. I don't know where the error in line 2 above came from. 
(If it helps: I encountered the same error when I tried to run **FindRelatedSentences.py** without having converted the .txt vectors to .bin)
Running **FindRelatedSentences.py**:
4. Works! But needs the .bin vectors to be copied to the **/generation/data** from **/data**

If you need me to post my output too, let me know.

**Comment by lenakmeth** [comment]
Ran **main.py** again, got this error:
`Traceback (most recent call last):`
`  File "main.py", line 34, in <module>`
`    print(se.execute_query(query[0], query[1]))`
`IndexError: list index out of range`

**Comment by eazteregg** [comment]
the invalid literal for int() error message is an error which has been excepted and simply printed out. I will change it to read something less worrying. Second error has also been fixed.
